services:

  mysql:
    image: mysql:8.0
    container_name: employee-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - employee-network


  backend:
    build:
      context: ./backend

    container_name: employee-backend
    restart: unless-stopped

    depends_on:
      - mysql

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    ports:
      - "8080:8080"

    networks:
      - employee-network


  frontend:
    build:
      context: ./frontend

    container_name: employee-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "80:80"

    networks:
      - employee-network


networks:
  employee-network:
    driver: bridge


volumes:
  mysql_data:
